### ISSUE TITLE
Add new locale  ?

### ISSUE THREAD

**Issue by mvnaz** [mojoaxel/bootstrap-select-country#12]
How can I integrate another locale to plugin? So countries will be displayed with another language ?

**Comment by mojoaxel** [comment]
> How can I integrate another locale to plugin? So countries will be displayed with another language ?

Sadly this is only possible by building your own version:
1. Fork and clone the repository and `npm install`.
2. Change the imported langs in [src/bootstrap-select-country.js#L4-L6](https://github.com/mojoaxel/bootstrap-select-country/blob/master/src/bootstrap-select-country.js#L4-L6)
3. Test your new version with: `npm start`.
4. Build a new bundle with `npm build`.
