### ISSUE TITLE
Return Country name instead of Country Code

### ISSUE THREAD

**Issue by gabimarti** [mojoaxel/bootstrap-select-country#17]
Is it possible to get the name of the country instead of its code in the result of the SELECT field?

**Comment by albirlak** [comment]
have solution?

**Comment by AdabanyaChinedu** [comment]
Is there like a configuration for this?

**Comment by mojoaxel** [comment]
You could use e.g. the package [country-list](https://www.npmjs.com/package/country-list) for this.
