### ISSUE TITLE
Option for data default with full country name?

### ISSUE THREAD

**Issue by JonathanNet** [mojoaxel/bootstrap-select-country#9]
Hi I also noticed that I cannot use full country name in data default, can it be added in this script like data-default="Denmark" ? :)

**Comment by mojoaxel** [comment]
No, you'll need to "translate" your name into a ISO_3166-2 country code like e.g. "DK".

Yu could use some existing library like e.g. [country-code-lookup](https://www.npmjs.com/package/country-code-lookup) for this.
